---
- name: "Iniciamos el servicio de nfs-utils"
  command: service nfs-utils restart

- name: "Creamos el directorio /data/nfs"
  file:
    path: /data/nfs
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Montamos la particion /data/nfs en el worker"
  mount:
    fstype: nfs
    opts: defaults
    state: mounted
    src: "{{ private_master_ip }}:/data/nfs"
    path: "/data/nfs"

- name: "Reiniciamos la VM para aplicar los cambios"
  reboot:
    reboot_timeout: 2
