---
- name: "Configuramos zona horaria Europe/Madrid"
  timezone:
    name: Europe/Madrid

- name: "Activamos NTP"
  command: timedatectl set-ntp true

- name: "Desactivamos SElinux"
  selinux:
    state: disabled

- name: "Instalamos chrony"
  package:
    name:
      - chrony
    state: latest

- name: "Actualizamos los paquetes"
  command: dnf -y update && dnf -y upgrade

- name: "Instalamos paquetes para NFS y wget"
  dnf:
    name:
      - nfs-utils
      - nfs4-acl-tools
      - net-tools
      - wget
      - iproute-tc
    state: latest

# TODO: Deberiamos usar esta tarea de Ansible, pero
# Hay un bug en el modulo de ansible "systemd y service", retorna este error "Service is in unknown state"
#
#- name: "Iniciamos servicio chronyd, nfs y firewalld"
#  systemd:
#    name: "{{ item }}"
#    state: started
#    enabled: yes
#    daemon_reload: yes
#  with_items:
#    - chronyd
#    - nfs-utils
#    - firewalld

- name: "Iniciamos servicio chronyd "
  command: service chronyd restart

- name: "Iniciamos servicio nfs-utils"
  command: service nfs-utils restart

- name: "Activamos el servicio de firewalld"
  command: systemctl enable firewalld

- name: "Iniciamos servicio firewalld"
  command: service firewalld restart

- name: "Habilitamos los puertos del firewall"
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - "rpc-bind"
    - "nfs"
    - "mountd"

- name: "Agregamos los hostnames del master y workers"
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - "{{ private_master_ip }} {{ hostname_master }}"
    - "{{ private_worker1_ip }} {{ hostname_worker1 }}"
    - "{{ private_worker2_ip }} {{ hostname_worker2 }}"

- name: "Reiniciamos la VM para aplicar los cambios"
  reboot:
    reboot_timeout: 2
