- hosts: all
  become: yes

  tasks:
    - name: Update all Centos8 virtual machines
      dnf: 
        name: "*"
        state: latest

    - name: Set timezone to Europe/Madrid
        timezone: Europe/Madrid

    - name: Install and enable chronyd
      dnf: 
        name: chrony
        state: latest
      systemd:
        name: chronyd
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Enable NTP
      command: timedatectl set-ntp true

    - name: Disable SElinux
      selinux:
        state: disabled

    - name: Install NFS modules
      dnf: 
        name: ['nfs-utils','nfs4-acl-tools']
        state: latest