- hosts: master
  become: yes

  tasks:
    - name: "Generamos el token join-command para unir los workers al master"
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: "Guardamos la salida en join-command"
      delegate_to: localhost
      copy:
        content: "{{ join_command.stdout_lines[0] }}"
        dest: "./join-command"
      become: no

- hosts: workers
  become: yes

  tasks:
    - name: "Reseteamos configuracion de kubeadm"
      command: kubeadm reset --force

    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      shell: /bin/bash /tmp/join-command.sh

    - name: Remove Join Command
      file:
        path: /tmp/join-command.sh
        state: absent
